export const ECOSYSTEM_APPS = [
  {
    id: 'prete',
    name: 'PRÊT·E',
    emoji: '🎒',
    description: 'Scénarios de préparation',
    url: 'https://pret.lacavernedurefractaire.fr',
    devUrl: 'https://pret.lacavernedurefractaire.fr',
    color: '#C96A5A',
  },
  {
    id: 'lynx',
    name: 'Lynx',
    emoji: '🐆',
    description: 'Anticipation & Alertes temps réel',
    url: 'https://lynx.lacavernedurefractaire.fr',
    devUrl: 'http://localhost:5176',
    color: '#3B82F6',
    current: true,
  },
  {
    id: 'smartcellar',
    name: 'SmartCellar',
    emoji: '🏪',
    description: 'Gestion intelligente de vos stocks',
    url: 'https://smartcellar.lacavernedurefractaire.fr',
    devUrl: 'https://smartcellar.lacavernedurefractaire.fr',
    color: '#F59E0B',
  },
  {
    id: 'progarden',
    name: 'ProGarden',
    emoji: '🌱',
    description: 'Potager & autoproduction',
    url: 'https://progarden.lacavernedurefractaire.fr',
    devUrl: 'https://progarden.lacavernedurefractaire.fr',
    color: '#22C55E',
  },
  {
    id: 'farmly',
    name: 'Farmly',
    emoji: '🐔',
    description: 'Élevage & autosuffisance animale',
    url: 'https://farmly.lacavernedurefractaire.fr',
    devUrl: 'https://farmly.lacavernedurefractaire.fr',
    color: '#92400E',
    disabled: true,
    comingSoon: true,
  },
  {
    id: 'herbogenius',
    name: 'HerboGenius',
    emoji: '🌿',
    description: 'Plantes, huiles & remèdes naturels',
    url: 'https://www.herbogenius.fr',
    devUrl: 'https://www.herbogenius.fr',
    color: '#16A34A',
  },
  {
    id: 'mentalgate',
    name: 'MentalGate',
    emoji: '🧠',
    description: 'Santé mentale & bilan psychologique',
    url: 'https://mentalgate.peaceandpause.fr',
    devUrl: 'https://mentalgate.peaceandpause.fr',
    color: '#7C3AED',
  },
  {
    id: 'primal',
    name: 'Primal',
    emoji: '🏋️',
    description: 'Préparation physique & fonctionnelle',
    url: null,
    devUrl: null,
    color: '#DC2626',
    disabled: true,
    comingSoon: true,
  },
  {
    id: 'partner',
    name: 'Partner',
    emoji: '🤝',
    description: 'Réseau partenaires & collaborateurs',
    url: null,
    devUrl: null,
    color: '#6B7280',
    disabled: true,
    comingSoon: true,
  },
];

export function getAppUrl(app) {
  const isDev = import.meta.env.DEV;
  return isDev ? (app.devUrl || app.url) : app.url;
}
